const GLOSSARIO_ORIGINAL = {
    "deus": "Elohim",
    "senhor": "Yahweh",
    "jesus": "Yeshua",
    "cristo": "HaMashiach",
    "espírito": "Ruach",
    "israel": "Yisrael",
    "jerusalém": "Yerushalayim",
    "terra": "Eretz",
    "céu": "Shamayim"
};

const REF_CRUZADAS = {
    "GEN-1-1": "João 1:1<br>Colossenses 1:16<br>Hebreus 11:3",
    "GEN-1-2": "Salmos 104:30<br>Isaías 40:13",
    "GEN-1-3": "2 Coríntios 4:6",
    "GEN-1-26": "Efésios 4:24<br>Colossenses 3:10",
    "JOH-1-1": "Gênesis 1:1<br>Apocalipse 19:13"
};

const BIBLE_METADATA = [
    {id: "GEN", name: "Bereshit (Gênesis)", chaps: 50, test: "OT"},
    {id: "EXO", name: "Shemot (Êxodo)", chaps: 40, test: "OT"},
    {id: "LEV", name: "Vayicrá (Levítico)", chaps: 27, test: "OT"},
    {id: "NUM", name: "Bemidbar (Números)", chaps: 36, test: "OT"},
    {id: "DEU", name: "Devarim (Deuteronômio)", chaps: 34, test: "OT"},
    {id: "JOS", name: "Yehoshua (Josué)", chaps: 24, test: "OT"},
    {id: "JDG", name: "Shoftim (Juízes)", chaps: 21, test: "OT"},
    {id: "RUT", name: "Rut (Rute)", chaps: 4, test: "OT"},
    {id: "1SA", name: "Shemuel I (1 Samuel)", chaps: 31, test: "OT"},
    {id: "2SA", name: "Shemuel II (2 Samuel)", chaps: 24, test: "OT"},
    {id: "1KI", name: "Melakhim I (1 Reis)", chaps: 22, test: "OT"},
    {id: "2KI", name: "Melakhim II (2 Reis)", chaps: 25, test: "OT"},
    {id: "1CH", name: "Divrei Hayamim I (1 Crônicas)", chaps: 29, test: "OT"},
    {id: "2CH", name: "Divrei Hayamim II (2 Crônicas)", chaps: 36, test: "OT"},
    {id: "EZR", name: "Ezra (Esdras)", chaps: 10, test: "OT"},
    {id: "NEH", name: "Nehemyah (Neemias)", chaps: 13, test: "OT"},
    {id: "EST", name: "Ester (Ester)", chaps: 10, test: "OT"},
    {id: "JOB", name: "Iyov (Jó)", chaps: 42, test: "OT"},
    {id: "PSA", name: "Tehilim (Salmos)", chaps: 150, test: "OT"},
    {id: "PRO", name: "Mishlei (Provérbios)", chaps: 31, test: "OT"},
    {id: "ECC", name: "Kohelet (Eclesiastes)", chaps: 12, test: "OT"},
    {id: "SNG", name: "Shir Hashirim (Cantares)", chaps: 8, test: "OT"},
    {id: "ISA", name: "Yeshayahu (Isaías)", chaps: 66, test: "OT"},
    {id: "JER", name: "Yirmeyahu (Jeremias)", chaps: 52, test: "OT"},
    {id: "LAM", name: "Eikhah (Lamentações)", chaps: 5, test: "OT"},
    {id: "EZK", name: "Yehezkel (Ezequiel)", chaps: 48, test: "OT"},
    {id: "DAN", name: "Daniel (Daniel)", chaps: 12, test: "OT"},
    {id: "HOS", name: "Hoshea (Oseias)", chaps: 14, test: "OT"},
    {id: "JOE", name: "Yoel (Joel)", chaps: 3, test: "OT"},
    {id: "AMO", name: "Amos (Amós)", chaps: 9, test: "OT"},
    {id: "OBA", name: "Ovadyah (Obadias)", chaps: 1, test: "OT"},
    {id: "JON", name: "Yonah (Jonas)", chaps: 4, test: "OT"},
    {id: "MIC", name: "Mikhah (Miqueias)", chaps: 7, test: "OT"},
    {id: "NAH", name: "Nahum (Naum)", chaps: 3, test: "OT"},
    {id: "HAB", name: "Havakuk (Habacuque)", chaps: 3, test: "OT"},
    {id: "ZEP", name: "Tsefanyah (Sofonias)", chaps: 3, test: "OT"},
    {id: "HAG", name: "Hagai (Ageu)", chaps: 2, test: "OT"},
    {id: "ZEC", name: "Zekharyah (Zacarias)", chaps: 14, test: "OT"},
    {id: "MAL", name: "Malakhi (Malaquias)", chaps: 4, test: "OT"},
    {id: "MAT", name: "Mattityahu (Mateus)", chaps: 28, test: "NT"},
    {id: "MAR", name: "Markos (Marcos)", chaps: 16, test: "NT"},
    {id: "LUK", name: "Loukas (Lucas)", chaps: 24, test: "NT"},
    {id: "JOH", name: "Yochanan (João)", chaps: 21, test: "NT"},
    {id: "ACT", name: "Maasei HaSheluchim (Atos)", chaps: 28, test: "NT"},
    {id: "ROM", name: "Romiyim (Romanos)", chaps: 16, test: "NT"},
    {id: "1CO", name: "Qorintiyim I (1 Coríntios)", chaps: 16, test: "NT"},
    {id: "2CO", name: "Qorintiyim II (2 Coríntios)", chaps: 13, test: "NT"},
    {id: "GAL", name: "Galatiyim (Gálatas)", chaps: 6, test: "NT"},
    {id: "EPH", name: "Efesiyim (Efésios)", chaps: 6, test: "NT"},
    {id: "PHI", name: "Filipiyim (Filipenses)", chaps: 4, test: "NT"},
    {id: "COL", name: "Colosiyim (Colossenses)", chaps: 4, test: "NT"},
    {id: "1TH", name: "Tesalonigiyim I (1 Tessalonicenses)", chaps: 5, test: "NT"},
    {id: "2TH", name: "Tesalonigiyim II (2 Tessalonicenses)", chaps: 3, test: "NT"},
    {id: "1TI", name: "Timoteos I (1 Timóteo)", chaps: 6, test: "NT"},
    {id: "2TI", name: "Timoteos II (2 Timóteo)", chaps: 4, test: "NT"},
    {id: "TIT", name: "Titos (Tito)", chaps: 3, test: "NT"},
    {id: "PHM", name: "Filemon (Filemón)", chaps: 1, test: "NT"},
    {id: "HEB", name: "Ivrim (Hebreus)", chaps: 13, test: "NT"},
    {id: "JAM", name: "Yaakov (Tiago)", chaps: 5, test: "NT"},
    {id: "1PE", name: "Kefa I (1 Pedro)", chaps: 5, test: "NT"},
    {id: "2PE", name: "Kefa II (2 Pedro)", chaps: 3, test: "NT"},
    {id: "1JO", name: "Yochanan I (1 João)", chaps: 5, test: "NT"},
    {id: "2JO", name: "Yochanan II (2 João)", chaps: 1, test: "NT"},
    {id: "3JO", name: "Yochanan III (3 João)", chaps: 1, test: "NT"},
    {id: "JUD", name: "Yehudah (Judas)", chaps: 1, test: "NT"},
    {id: "REV", name: "Hazon (Apocalipse)", chaps: 22, test: "NT"}
];